requests:
  google_get:
    url: google.com
    scheme: https
    path: /
  private_server_get:
    url: localhost
    port: 2222
    scheme: http
    path: /opl/health
    headers:
      Authorization: Bearer {{ .PRIVATE_SERVER_ENV_VAR }}_
